#!/bin/bash

directory="Executables"

declare -A extensions

extensions=( ["c"]="1" 
			 ["py"]="1"
			 ["cpp"]="1"
			 ["java"]="1"
			 ["js"]="1"
			 ["mat"]="1"
			 ["sh"]="1"
			 ["go"]="1"

			 ["mp4"]="2" 
			 ["mpeg"]="2"
			 ["mkv"]="2"
			 ["flv"]="2"
			 ["avi"]="2"

			 ["img"]="3"
			 ["jpeg"]="3"
			 ["png"]="3"
			 ["gif"]="3" 

			 ["pdf"]="4"
			 ["txt"]="4"
			 ["doc"]="4"
			 ["pptx"]="4"
			 ["xls"]="4"
			 ["md"]="4"

			 ["zip"]="5"
			 ["tar"]="5" 
			 ["deb"]="5"
			 ["rar"]="5"
			 ["tgz"]="5"
			 ["xz"]="5"
			 ["gz"]="5"
				)

create_dir () {

	local directory=$1

	if [[ -e "$directory" ]]
	then
		echo "Directory exists"
	else
		mkdir $directory
		echo "Directory Created"
	fi

}

get_cat () {

	local ext=$1
	
	local val=0

	for key in "${!extensions[@]}"; do
        if [[ $key == $ext ]]; then
			val=${extensions[$key]}
			return $val
        fi
    done
		
	return $val
}


organize_dir (){
	local file="$1"
	local filename=$(basename "$file") #get the filename from address
	local ext=${filename##*.}  #get the extension from filename

	local ext="${ext,,}" #convert the extension to lowercase
	
	if [[ ! "$ext" == '' && ! -d "$filename" ]]
	then
		get_cat "$ext"
		local val=$?
		echo $val
	
	if [[ "$val" == "1" ]]
	then
		dirname="Programming"
		if [[ ! -d "$dirname" ]]
		then
			create_dir $dirname 
		fi
		mv "$filename" $dirname 
	elif [[ "$val" == "2" ]]
	then
		dirname="Videos"
		if [[ ! -d "$dirname" ]]
		then
			create_dir $dirname 
		fi
		mv "$filename" $dirname 
	elif [[ "$val" == "3" ]]
	then
		dirname="Images"
		if [[ ! -d "$dirname" ]]
		then
			create_dir $dirname 
		fi
		mv "$filename" $dirname 
	elif [[ "$val" == "4" ]]
	then
		dirname="Documents"
		if [[ ! -d "$dirname" ]]
		then
			create_dir $dirname 
		fi
		mv "$filename" $dirname 
	elif [[ "$val" == "5" ]]
	then
		dirname="Compressed"
		if [[ ! -d "$dirname" ]]
		then
			create_dir $dirname 
		fi
		mv "$filename" $dirname 
	elif [[ "$val" == "0" ]]
	then
		dirname="Others"
		if [[ ! -d "$dirname" ]]
		then
			create_dir $dirname 
		fi
		mv "$filename" $dirname 
	fi

	fi
}

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

for file in $(ls | grep -v $(basename "$0"))
do

if [[ -x "$file" && ! -d "$file" && $(grep -r1 '#!/bin/bash' "$file") ]]
then
	echo "in exec"
	create_dir $directory
	mv "$file" $directory
else
	organize_dir "$file"
fi

done

IFS=$SAVEIFS
